{{- range $app, $values := dict "nodejs" .Values.nodejsApp "python" .Values.pythonApp "php" .Values.phpApp }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $app }}
  template:
    metadata:
      labels:
        app: {{ $app }}
    spec:
      containers:
        - name: {{ $app }}
          image: {{ $values.image }}
          ports:
            - containerPort: {{ $values.port }}
---
{{- end }}
